vich_uploader:
    db_driver: orm

    mappings:
        hero_pictures:
            uri_prefix:         '%app.path.hero_pictures%'
            upload_destination: '%kernel.project_dir%/public%app.path.hero_pictures%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
